<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\JustDanceEditor.Formats.JDNextPC\JustDanceEditor.Formats.JDNextPC.csproj" />
		<ProjectReference Include="..\JustDanceEditor.Formats.JDI\JustDanceEditor.Formats.JDI.csproj" />
		<ProjectReference Include="..\JustDanceEditor.Formats.UbiArt\JustDanceEditor.Formats.UbiArt.csproj" />
		<ProjectReference Include="..\JustDanceEditor.Formats.Unity\JustDanceEditor.Formats.Unity.csproj" />
		<ProjectReference Include="..\JustDanceEditor.IPK\JustDanceEditor.IPK.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Nerdbank.GitVersioning" Version="3.9.50" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
	</ItemGroup>
</Project>
