<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="BCnEncoder.Net.ImageSharp" Version="1.1.3" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CrnLib\CrnLib.csproj" />
	</ItemGroup>
</Project>
