using JustDanceEditor.Formats.JDI;
using JustDanceEditor.Formats.JDI.Serialization;
using JustDanceEditor.Formats.Unity;

namespace JustDanceEditor.Converter.Formats;

internal sealed class JdiPackageFormat : IJdiFormat
{
    public string DisplayName => "JDI Package";
    public JdiFormatKind Kind => JdiFormatKind.JDI;
    public bool CanImport => true;
    public bool CanExport => true;

    public Task<JdiImportResult> ImportAsync(ConversionRequest request, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        string folder = LocateIntermediateFolder(request.InputPath);
        IntermediateSongPackage package = IntermediatePackageSerializer.LoadFromFolder(folder);
        JdiConversionHelpers.EnsureSongName(request, package);
        return Task.FromResult(new JdiImportResult(
            package,
            JdiFormatKind.JDI,
            MaterializedRoot: folder));
    }

    public Task ExportAsync(JdiImportResult importResult, ConversionRequest request, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(importResult);
        ArgumentNullException.ThrowIfNull(request);

        string targetFolder = !string.IsNullOrWhiteSpace(importResult.SuggestedOutputFolder)
            ? importResult.SuggestedOutputFolder!
            : JdiConversionHelpers.BuildSongOutputFolder(request.OutputPath, importResult.Package.Metadata);

        if (Directory.Exists(targetFolder))
            Directory.Delete(targetFolder, true);
        Directory.CreateDirectory(targetFolder);

        switch (importResult.SourceFormat)
        {
            case JdiFormatKind.UbiArt:
            case JdiFormatKind.JDI:
                if (!string.IsNullOrWhiteSpace(importResult.MaterializedRoot))
                    JdiConversionHelpers.CopyDirectoryContents(importResult.MaterializedRoot!, targetFolder);
                break;
            case JdiFormatKind.Unity:
                UnityAssetMaterializer.Materialize(importResult.Package, request.InputPath, targetFolder);
                break;
            default:
                throw new NotSupportedException($"Exporting from {importResult.SourceFormat} to JDI is not supported.");
        }

        IntermediatePackageSerializer.WriteToFolder(importResult.Package, targetFolder);
        return Task.CompletedTask;
    }

    private static string LocateIntermediateFolder(string inputPath)
    {
        if (string.IsNullOrWhiteSpace(inputPath))
            throw new ArgumentException("Input path cannot be empty.", nameof(inputPath));

        if (IsIntermediateFolder(inputPath))
            return inputPath;

        string nested = Path.Combine(inputPath, "Intermediate");
        if (IsIntermediateFolder(nested))
            return nested;

        try
        {
            foreach (string manifest in Directory.EnumerateFiles(inputPath, "manifest.json", SearchOption.AllDirectories))
            {
                string? folder = Path.GetDirectoryName(manifest);
                if (!string.IsNullOrEmpty(folder) && IsIntermediateFolder(folder))
                    return folder;
            }
        }
        catch (UnauthorizedAccessException)
        {
        }

        throw new DirectoryNotFoundException($"Could not find an intermediate package under '{inputPath}'. Ensure the folder contains a manifest.json generated by the converter.");
    }

    private static bool IsIntermediateFolder(string folder)
    {
        if (string.IsNullOrWhiteSpace(folder) || !Directory.Exists(folder))
            return false;

        string manifestPath = Path.Combine(folder, "manifest.json");
        return File.Exists(manifestPath);
    }
}
