<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
		<PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="Nerdbank.GitVersioning" Version="3.9.50" />
	</ItemGroup>
</Project>
