using Avalonia.Controls.ApplicationLifetimes;
using JustDanceEditor.Editor.Attributes;
using JustDanceEditor.Editor.Services;
using JustDanceEditor.Editor.ViewModels;

namespace JustDanceEditor.Editor.ViewModels.Tools;

[RunCommand("Open Map Folder...", "File", priority: 100)]
public class OpenMapFolderCommand : IRunCommand
{
    public bool CanRun(ITimelineContextService? timelineContext) => true;

    public void Run(ITimelineContextService? timelineContext)
    {
        try
        {
            var desktop = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            var main = desktop?.MainWindow;
            if (main?.DataContext is MainWindowViewModel mvm)
            {
                // Use existing command generated by [RelayCommand]
                mvm.OpenMapCommand.Execute(null);
            }
        }
        catch
        {
            // Swallow to avoid breaking menu invocation
        }
    }
}