# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore JustDanceEditor.UI/JustDanceEditor.UI.csproj
    - name: Publish
      run: dotnet build -c Release -r win-x64
    - name: Test
      run: dotnet test JustDanceEditor.UI/JustDanceEditor.UI.csproj --verbosity normal
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: JustDanceEditor.UI/bin/Release/net8.0/
