name: Build Solution

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 2022

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Update this to match your .NET version

    - name: Restore NuGet packages
      run: nuget restore YourSolution.sln

    - name: Build solution
      run: msbuild YourSolution.sln /p:Configuration=Release
